name: Send Daily Affirmation

on:
  schedule:
    - cron: "30 6 * * *"  # Run daily at 6:30 AM UTC
  workflow_dispatch:       # Allow manual runs

jobs:
  send_affirmation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Affirmation Script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python send_affirmation.py
