name: Send Daily Affirmation

on:
  schedule:
    # Runs every day at 9:00 AM UTC
    - cron: "0 9 * * *"

jobs:
  send_affirmation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Run Affirmation Script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python send_affirmation.py
